export const SET_PENDING = 'SET_PENDING'
export const SET_ID = 'SET_ID'
export const SET_COOKIES = 'SET_CCOKIES'
export const SET_UNIQUES = 'SET_UNIQUES'
export const SET_CHROME_BROWSER = 'SET CHROME BROWSER'
export const SET_INSTALLED = 'SET_INSTALLED'
